#!/bin/bash
#
# NAME
#     etime -- calculate minutes since a given epoch
#
# SYNOPSIS
#     etime [-r epoch_seconds]
#
# DESCRIPTION
#     etime calculates the number of minutes since a given epoch or starting
#     point, which itself is measured in seconds since the unix epoch.  Values
#     returned from etime are used as unique canonical ids for each page and
#     post within the site. The script is primarily used by the `post` script
#     (also found in this directory), but is factored out separately as it can
#     be useful on its own, e.g. when creating and dating a post by hand.
#
# OPTIONS
#     -e epoch_seconds
#         The epoch from which all times should be calculated. May be a birth
#         date, inception of a website or company, etc.
#
#     -r relative_unix_time
#         Calculate time relative to our epoch since (or until) the given date,
#         expressed as unix epoch seconds.  When etime is invoked without the
#         -r option, the current value of `date +%s` is used as the default
#         value of relative_unix_time. Note that '-r' is borrowed from the
#         `date` command's option of the same name due to their similar
#         semantics.
#
# ENVIRONMENT
#     The following environment variables affect the execution of etime:
#
#     EPOCH
#         Alternative to -e option. At least one of these must be provided, and
#         if both are, then the -e value overrides.
#
# SEE ALSO
#     post, date
#
epoch=$EPOCH

while getopts ":e:r:" opt; do
    case $opt in
        e)
            epoch=$OPTARG
            ;;
        r)
            relative_date=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ -z "$epoch" ]; then
    echo "Either env variable EPOCH or command option -e must be provided"
    exit 1
fi

if [ -n "$relative_date" ]; then
    let now=$relative_date
else
    let now=$(date +%s)
fi
let etime=($now-$epoch)/60
echo -n $etime
exit 0
